name: Tests

on:
  push:
    branches:
      - main

jobs:
  basic:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: make -j $(grep -c ^processor /proc/cpuinfo)
